### ISSUE TITLE
Move Tags to the Sidebar

### ISSUE THREAD

**Issue by nickhamze** [WordPress/wporg-theme-directory#103]
In the plugin repo you have the tags on the sidebar and I think they make a lot of sense there. What do you think about moving the features tags there too.

<img width="363" alt="Screenshot 2024-05-30 at 6 23 23 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/158918/59f35c41-31de-4e31-b71e-1bb73f92c4cd">

**Comment by ryelle** [comment]
I'm inclined to leave it where it is to match the current site. Plus, themes tend to have many more tags than plugins, so this would get very crowded.

Here's a hacked-together version:

<img width="770" alt="Screenshot 2024-05-31 at 11 25 44 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/30dacf19-87eb-4691-9921-c00c5c9d1626">

 @WordPress/meta-design — what do you think?

**Comment by nickhamze** [comment]
I think it makes much more sense there. I also think we should remove about half the allowed tags. Who is honestly clicking on "Custom Menu" or "Sticky Post" as a tag in 2024? I think if you removed the ones that never get clicked on or don't make sense that list would be much more manageable and useful. 

But I can guess your reply "We aren't looking to remove any functionality" :) . The visual redesign is nice but if you aren't making it better/easier/faster to find themes I don't get the point of any of this.

**Comment by fcoveram** [comment]
Agree with @ryelle on keeping it as is and perhaps address this in the future once we start talking about the next stage of the repositories sections of the site.

**Comment by ryelle** [comment]
I'm going to close this issue then, future iteration ideas can be suggested in [the discussion section](https://github.com/WordPress/wporg-theme-directory/discussions).
