### ISSUE TITLE
Commercial themes tile should have external link indicator.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-theme-directory#108]
**Describe the bug**
When viewing the commercial theme company page, we use the same UI as the main grid. The difference here is that those link to external sources. We should add "↗" to those links for consistency with the site.

**To Reproduce**
1. Go to https://wordpress.org/themes/commercial/
2. Click on a theme tile
3. Notice you left wp.org.

**Screenshots**
<img width="414" alt="Screenshot 2024-06-05 at 9 28 28 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/55662a62-0109-4b2b-b0d4-0d6cf211459a">

**Comment by ndiego** [comment]
+1 on this.
