### ISSUE TITLE
New default OpenGraph image to match refresh?

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-theme-directory#117]
The current Theme Directory has no social media embed content on archive pages (single pages use the theme info & screenshot). For other sites, we've added default images ([main site](https://wordpress.org/files/2024/04/wordpress-homepage-ogimage-202404.png), [pattern directory](https://s.w.org/patterns/files/2024/04/patterns-ogimage.png)). Should there be a default image for the Theme Directory too?

See related issue from Pattern Directory https://github.com/WordPress/pattern-directory/issues/659 — however, I'm only realizing now, we use this image across the Rosetta (non-English) sites as well, so ideally it would not have English text. I could also use one image for English, and a different one for the rest of the rosetta sites.

cc @WordPress/meta-design

**Comment by fcoveram** [comment]
If I remember correctly, we talked somewhere in a ticket to show only text content in the image. Perhaps @joen or @thetinyl remember this decision.

My understanding is that this image is always inside a container with text content describing the page users are landing on. If that is correct, then the Rosetta site's point is strong enough to shift to non-text content for this (Theme Directory) and all the rest of the sections already implemented.

Otherwise, we could include a Figma file in [WordPress profile](https://www.figma.com/@wordpressorg) with the template so that anyone can generate the images in other languages.

**Comment by ryelle** [comment]
> My understanding is that this image is always inside a container with text content describing the page users are landing on.

I'm not sure if this is always true— I [use this site to test](https://www.opengraph.xyz/url/https%3A%2F%2Fwordpress.org%2Fthemes%2F%3Fnew-theme%3D1) and it appears that while FB and discord show the site title & description, linkedin only shows title, and twitter only shows the image… though the post it's included in would have some context, likely.

> we could include a Figma file in [WordPress profile](https://www.figma.com/@wordpressorg) with the template so that anyone can generate the images in other languages.

That _could_ work, we could ask translators with access to upload the image to their main [locale].w.org site and allow the URL to be translated through GlotPress… I imagine only a few people will do that, though. There's also no way to enforce that whatever image a team uses came from the figma template.

I think we can get away with an English text image like [the pattern directory](https://s.w.org/patterns/files/2024/04/patterns-ogimage.png) for launch, at least.

**Comment by nukaga** [comment]
> we could include a Figma file in [WordPress profile](https://www.figma.com/@wordpressorg) with the template so that anyone can generate the images in other languages.

I think this is great, I was trying to figure out how to create the featured image for a Japanese news blog on WordPress.org.
With the Figma template, I can create the featured image with Japanese translations.
It would be the same in other languages.

<img width="719" alt="スクリーンショット 2024-06-13 16 01 41" src="https://github.com/WordPress/wporg-theme-directory/assets/3480985/13cea712-38cf-45b5-838b-a0160ff86b6b">

On the right is an image of a news blog translated into Japanese and posted to X. I would like to use the same template for this as for the English Featured Image.

**Comment by thetinyl** [comment]
I'm not sure there was ever a final decision on this, but [this is the ticket](https://github.com/WordPress/wporg-developer/pull/478) I can remember where this came up previously (for Dev Resources).

**Comment by ryelle** [comment]
We'll be using this image for now, and will follow up after launch with a template and translation process for the Rosetta sites.

![](https://github.com/WordPress/wporg-theme-directory/assets/541093/3c3d83ad-4e31-4927-b012-42a3f6289007)

**Comment by fcoveram** [comment]
I had the chance to talk a little bit more about this with @nukaga at WCEU, and it seems that sharing a Figma file with templates is the best approach.

I echo @ryelle's concern about loosing some control about the image submitted, but I think it's part of value of a community owning the site. To diminish the risk of cases like this, we could ask for updating handbooks and other related documentation to reinforce the design guideline. If the image update happens publicly, we can potentially push it back if folks consider it inappropiate.

**Comment by fcoveram** [comment]
Oh. Your comment @ryelle arrived while I was typing 😅

**Comment by ryelle** [comment]
> To diminish the risk of cases like this, we could ask for updating handbooks and other related documentation to reinforce the design guideline. If the image update happens publicly, we can potentially push it back if folks consider it inappropiate.

Yeah, documentation will be a big help, I think. Also, I think it's _very unlikely_ that someone would do something negative, but I want to make sure we have guardrails in place. Something like, the image must be served from the wordpress.org domain, so that only users with access to upload images can set this.

I'm going to close this issue with the basic image update, but I've created https://github.com/WordPress/wporg-mu-plugins/issues/631 for a central place to manage the translation.
