### ISSUE TITLE
Typo "avgerage" in stars rating

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/wporg-theme-directory#119]
The translation community found this typo: 
`The avgerage rating of this theme displayed as stars.`

in /themes/wporg-themes-2024/src/ratings-stars/block.json?marks=0#L0

Reported by profiles.wordpress.org/andyamado

**Comment by StevenDufresne** [comment]
Fixed in [cfba6e2](https://github.com/WordPress/wporg-theme-directory/commit/cfba6e208ca5789b25f8ebeca72644c835ba8c9a)
