### ISSUE TITLE
Use %d instead of %s for count of search results in block-config.php

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/wporg-theme-directory#122]
In 
https://github.com/WordPress/wporg-theme-directory/blob/trunk/source/wp-content/themes/wporg-themes-2024/inc/block-config.php

The number of themes found for a search uses %s to inject the count of themes found into a heading.

Although this will work, it's cleaner to use %d. Then translators will more easily see that the variable, indeed, will just show a number.

**Comment by ryelle** [comment]
When [the string is actually output](https://github.com/WordPress/wporg-mu-plugins/blob/5c6616a1b2093dcf1e51e097a4330d5622395d36/mu-plugins/blocks/query-total/index.php#L50-L63), it uses `number_format_i18n`, so it's a string - if we switch to `%d` the int validation will break the display.

**Comment by tobifjellner** [comment]
Oh. Then we can close this ticket :)
