### ISSUE TITLE
Can't navigate patterns on mobile device.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-theme-directory#131]
**Describe the bug**
If I click a pattern from the pattern grid, it will load it in the preview but I don't see a way to navigate patterns on my mobile device in the previewer. 

**Screenshots**
<img src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/e9e230d8-8956-4bc3-ac1f-2519f450328c" width="300">

**Comment by ryelle** [comment]
Good point, we only expose style variations on mobile. I'm inclined to say the current process is fine*— users can swipe back to the pattern list on the detail page and click another one, then swap out style variations in the previewer.

@WordPress/meta-design Do you think we need to change anything here for the "refresh" version? (I'm sure when we get to the full redesign I think the previewer will be first in line 🙂)

**Comment by jasmussen** [comment]
I'd think this fine for now, for the arguments Kelly presents. If we were to show the row of patterns at the bottom, then you wouldn't be able to test them in the various style variations. There's room to rethink the previewer on a larger scale, which may be better to invest in, than this particular iteration.

**Comment by ryelle** [comment]
I'm going to close this issue, we can open a new discussion or just wait until the full redesign to change anything here.
