### ISSUE TITLE
Template column width: adjust center column pages.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#134]
The current Page template has a max-width of 680px, center aligned:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/4a43c917-b377-4380-9e53-a5291575fc72)

The grid of thumbnails has a max-width of 1160:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/ae1bac0b-9ffc-4dfa-b9cf-1bba9bdd5967)

Individual theme pages are also 1160:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/fb3806e9-3160-4fe0-bd3e-5e9f2e660857)

On pages like Commercial themes, the flow gets disrupted a little bit because both types of layout are present:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/de429a05-90e1-441e-a7fb-9b2ca001bef5)

The mix of these two causes a bit of a tipping layout. Suggestion: unify on 1160px across, but with a left aligned column for content, that's not quite full-wide. Here's an example from [the original directory design](https://www.figma.com/design/DQuNUBmyVbbtJNOqCSrAPH/Themes?node-id=3260-7800&t=jAGOy3PTbTgdvFkO-1):

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/7b46873f-8f7e-4efd-82ce-6b8c23ddba48)

In that particular image, the left aligned column inside is 680px:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/f9349bd3-7858-4fa2-b663-2b6cd27a2ade)

This matches similar designs for [Documentation](https://www.figma.com/design/iM8I9yAYbwjbc9q9b2WWui/Documentation%2FHelpHub?node-id=4535-2401&t=XspFdBRfqzcDEcoj-1):

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/8a927767-7f0d-4da4-93d0-39818ecc1775)

Whether it's 680 or something closer to the left-column width of [theme permalinks](https://wordpress.org/themes/twentynineteen/), or even the 800px from [the Learn mockups](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-42814&t=2FxXymxY7x95hKEs-1), the important part is that it's a left aligned column inside a container that's 1160px. Learn example:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/bb9e1cd3-5349-424c-b0d2-ad6e7a529a29)

**Comment by ndiego** [comment]
I think this approach works. It would look like this. The Group just needs to be aligned wide and the justification set to left. The screenshot just shows the top of the page, but the bottom text would be the same.

<img width="1568" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/4832319/8ae405f5-318f-41b5-af89-d1e2ea978eea">

**Comment by ryelle** [comment]
I can make that change, but I'm having trouble following all the screenshots above— is that the only change required here?

**Comment by ryelle** [comment]
Oh, does this need to happen for all pages?

**Comment by jasmussen** [comment]
> Oh, does this need to happen for all pages?

I think that would be ideal. I don't think we have many pages where we have the 680px column plainly centered. It's always assumed to have either whitespace, or a sidebar (not present on the theme directory) in the area on the right.
