### ISSUE TITLE
"Help translate" bar is very big

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#136]
On the them directory landing page, the language bar is 32px tall and blue and 12px font size:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/06c6776d-4c21-4005-ae9c-44d764baec99)

On the theme directory, language bar (which includes here a "help translate" CTA) is 54px tall and yellow 14px font size:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/a68b49ae-a4d4-43b5-82c8-53c092ab7f44)

It's clear that the language bars are different types; one is for the directory itself, one is for the theme and with a translation contribution callout. This fact suggests that we should likely redesign, more holistically, the latter. 

But in the mean time, can we unify the height and font sizes? 

Can it also be "Help improve the translation." instead of "Help improve the translation!" (exclamation to period)?

**Comment by ryelle** [comment]
@jasmussen This "prominent style" was added for the Plugin Directory, approved by @fcoveram (see see https://github.com/WordPress/wordpress.org/issues/301). I've updated this in the theme directory to match the behavior: a small banner on archives/pages, and a larger banner on single plugins.

Should it change back in both places? Just on themes? Do you have a proposal for a better "prominent" banner?

**Comment by jasmussen** [comment]
I didn't see that, sorry about that. I'm happy to defer to Francisco; I do think it's a little big, but I'm also happy to try keeping it as is. The alternative as I alluded to in the issue here is to rethink: what is the goal of this "help translate" bar, and could it live elsewhere, perhaps as a CTA in the sidebar? Given the ping, Francisco will have a chance to see this when he's back from AFK, and share his thoughts. So feel free to close this one in the mean time if that's the preference, then we can open a new issue depending on where we land.

**Comment by ryelle** [comment]
Okay, I'll close this. The language suggestion banner lives in wporg-mu-plugins, so if you decide to change it, open a new issue there.
