### ISSUE TITLE
Hover/focus style for patterns, especially on dark backgrounds, has artifacts

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#139]
This is in nit-picky territory, and it's probably related to https://github.com/WordPress/wporg-theme-directory/issues/128#issuecomment-2175270424 and how hover/focus styles are drawn on thumbnail previews. 

But in case a refactor allows us to improve things, there are small edge artifacts on thumbnails. It's not immediately visible:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/b7c0bc37-a2ee-41ba-8687-f827ccfbdbbe)

But if you zoom in, you can see the white artifacts:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/b9755599-b24d-4996-b00a-495ca1da32a1)

This is likely from the focus style being stacked on top of a white border, using a pseudo element, rather than being drawn on the parent instead.

**Comment by ryelle** [comment]
Moved to #128.
