### ISSUE TITLE
Theme preview: Style variations exceed container width, creating horizontal scrollbar

### ISSUE THREAD

**Issue by Clorith** [WordPress/wporg-theme-directory#141]
**Describe the bug**
The style variations in the theme previewer uses a grid display, but the two column layout causes a horizontal scroll bar.

**To Reproduce**
1. Go to https://wordpress.org/themes/twentytwentyfour/preview/
2. Observe the sidebar with style variations and patterns, and a horizontal scrollbar at the bottom.

**Expected behavior**
The style variation buttons should either shrink in size to fit within the container, or collapse into a single column.

**Screenshots**
![Screenshot displaying the horizontal scrollbar in the left hand sidebar area with the Google Chrome browser](https://github.com/WordPress/wporg-theme-directory/assets/468735/a1d3fa04-337e-4979-9f28-51dd43f6c226)

**Desktop (please complete the following information):**
 - OS: Windows 10 (22H2)
 - Browser: Google Chrome
 - Browser Version: 125.0.6422.142
 - Browser: Microsoft Edge
 - Browser Version: 126.0.2592.61
 - Browser: Firefox
 - Browser Version: 127.0.1

**Additional context**
Tested on relatively large resolution desktop monitors with 1920px and 2560px widths. This appears to happen due to the vertical scrollbar in the left hand sidebar being present, when switching to responsive mode in dev tools, where the scrollbar behaves like on a non-desktop device, or as is the default on Mac's, the horizontal scroll is not there.

**Comment by ryelle** [comment]
I noticed this while fixing #140, so it'll be fixed on production shortly :)
