### ISSUE TITLE
Layout: Landing Page

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-theme-directory#15]
[Figma link](https://www.figma.com/file/DQuNUBmyVbbtJNOqCSrAPH/Themes?node-id=2386%3A31025&t=I6uUwo2R6VQO0HX8-4)

![Themes - Landing](https://user-images.githubusercontent.com/7200686/215924723-6c0163f0-90f1-4385-9fae-5f03a984e968.jpg)
![Themes - Landing(1)](https://user-images.githubusercontent.com/7200686/215924710-ce23e64c-e85c-45bc-9ce1-817cefe40931.jpg)
<img width="375" alt="Mobile - Landing" src="https://user-images.githubusercontent.com/7200686/215924696-03dc0e2e-8257-4fc5-9176-cac8b1ae0b88.png">

**Comment by beafialho** [comment]
This one is still under discussion in #13.

**Comment by ryelle** [comment]
Even if the filter is under discussion, it's probably safe to start building out the blocks needed for the grids:

- [ ] Theme screenshot block
- [ ] Theme name block (probably can use the core post-title block)
- [ ] Available styles block
- [ ] Favorite block

The filter bar is tracked in https://github.com/WordPress/wporg-theme-directory/issues/17

Pulling it all together to display will be a Query block (or two).
