### ISSUE TITLE
Inconsistent name in local nav

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-theme-directory#152]
Initially reported [here](https://github.com/WordPress/Learn/issues/2622#issuecomment-2219810417) in [Learn#2622](https://github.com/WordPress/Learn/issues/2622)

**Describe the bug**
"Themes" is called differently across sections and pages. Here is a table pointing out the places where this occurs.

| Menu item in global header | Hero section in Homepage | Section name in local nav |
|:---|:---|:---|
| Themes | Themes | Theme Directory |

I would change the local nav version to "Themes" and be consistent with how it works in Patterns

**Comment by thetinyl** [comment]
> I would change the local nav version to "Themes" and be consistent with how it works in Patterns

Just chiming in to agree with this suggestion.
