### ISSUE TITLE
Duplicate theme variations on Twenty Twenty-Five preview

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-theme-directory#158]
Go to https://wordpress.org/themes/twentytwentyfive/preview/
Scroll down in the sidebar to "Style variations", see that the first 8 (after "Default") are repeated.
They are the same, linking to the same variation links (e.g., both green cards link to https://wordpress.org/themes/twentytwentyfive/preview/?style_variation=afternoon)

![Image](https://github.com/user-attachments/assets/84f1a1b9-5da2-4d0e-8b9f-0f537270f73f)

Not sure yet if this is an issue in parsing or display, or if this affects any other themes.

**Comment by ryelle** [comment]
Got a report from @ianstewart that this also causes the screenshot to appear twice when the style variation preview is selected:

![Image](https://github.com/user-attachments/assets/928ba6dd-13d1-467f-80b0-e9a730aa5d16)

**Comment by ryelle** [comment]
Looks like the issue is that the style variations returned by `WP_Theme_JSON_Resolver::get_style_variations();` [here](https://meta.trac.wordpress.org/browser/sites/trunk/wp-themes.com/public_html/wp-content/plugins/style-variations/inc/styles-endpoint.php#L6) is including both the root `styles/*.json` files and the files inside the subfolders — which is why there are 24 variations instead of 9, it includes the 7 typography and 8 color json files. The issue is that the color palettes and full style variations use the same names, which creates the duplicates.

There should only be these options:

![Image](https://github.com/user-attachments/assets/48ad57f4-646a-461c-94d9-5bf1f6a73312)

I'm not sure if it's a core bug that `get_style_variations` returns the typography and palette options, or if this needs more processing.

**Comment by carolinan** [comment]
Thank you!
