### ISSUE TITLE
Translations without a Rosetta site are not listed

### ISSUE THREAD

**Issue by timse201** [WordPress/wporg-theme-directory#159]
Portuguese (Portugal, AO90), Dutch (Formal) and German (Formal) are not listed on available language packs. If language packs are only available for German formal and not for default, "German" is not displayed.

https://wordpress.org/themes/twentytwentythree/
![Image](https://github.com/user-attachments/assets/4a8ab2b8-defb-4804-82f9-b0d452effa16)

**Comment by ryelle** [comment]
These links are not download links, they're links to the different Rosetta sites. If a locale doesn't have a site, there would be nothing to link to here.

This is the same as on plugins, and likely anything we decide on should be done in both places - so I'm going to close this issue to keep everything on https://github.com/WordPress/wordpress.org/issues/424.
