### ISSUE TITLE
Layout: Search Results

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-theme-directory#16]
[Figma](https://www.figma.com/file/DQuNUBmyVbbtJNOqCSrAPH/Themes?node-id=2224%3A26668&t=I6uUwo2R6VQO0HX8-4)

Screenshots:

| Search results | No Results |
|---|---|
| ![Themes - Search results](https://user-images.githubusercontent.com/7200686/215925532-db4724f7-98ab-47df-be6a-a5438a100297.jpg) | ![Themes - Search no results](https://user-images.githubusercontent.com/7200686/215925568-60001f26-b5d7-4a36-ac74-e561780db91e.jpg) |
| <img width="375" alt="Mobile - Search results" src="https://user-images.githubusercontent.com/7200686/215925601-0247f9fb-ffd5-4e11-8fd2-c8db72ee7761.png"> | <img width="375" alt="Mobile - Search" src="https://user-images.githubusercontent.com/7200686/215925613-e54113d3-ab13-4e76-b642-5b8f85cb9995.png"> |

**Comment by ryelle** [comment]
Once the components are built for the homepage (#15) & filter bar (#17), this should be just a matter of setting up the search template to use those.
