### ISSUE TITLE
Layout: Filter & Sorting

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-theme-directory#17]
[Figma](https://www.figma.com/file/DQuNUBmyVbbtJNOqCSrAPH/Themes?node-id=2224%3A25893&t=I6uUwo2R6VQO0HX8-4)

Screenshots:

| No filters | Filters open | Filters selected | Filters applied | Sorting open |
|---|---|---|---|---|
| <img width="1317" alt="Screenshot 2023-02-03 at 5 56 28 PM" src="https://user-images.githubusercontent.com/541093/216726485-edd3b2a5-5bcc-4035-94b2-0ab47fe371b3.png"> | ![Themes - Filter](https://user-images.githubusercontent.com/7200686/215926439-d1c2f8e0-d209-48f6-b6c2-4c4798c7cb16.jpg) | ![Themes - Selecting filters](https://user-images.githubusercontent.com/7200686/215926436-2fa89a1e-a338-40e9-b421-c738365daeb1.jpg) | ![Themes - Applied filters](https://user-images.githubusercontent.com/7200686/215926432-5cd1a437-d59e-422f-99ab-44806c3773a6.jpg) | ![Themes - Sorting](https://user-images.githubusercontent.com/7200686/215926424-234ea7e9-435a-4d4d-b52e-682454a0fd72.jpg) |

Mobile
| No filters | Filters open | Filters selected | Filters applied | Sorting open |
|---|---|---|---|---|
| <img width="373" alt="Screenshot 2023-02-03 at 5 56 15 PM" src="https://user-images.githubusercontent.com/541093/216726548-aa9d3b7b-7b7d-400d-8afe-7c9faeccd8a4.png"> | ![Mobile - Filter](https://user-images.githubusercontent.com/541093/216726072-303e476a-a16b-4a65-adbc-dee394104cb3.png) | ![Mobile - Filters applied](https://user-images.githubusercontent.com/541093/216726073-0fbeb2ff-2480-4a66-8fb3-00e56f31f41a.png) | ![Mobile - Applied filters](https://user-images.githubusercontent.com/541093/216726070-6cc5fbc0-3d94-4b39-9ffb-b746a1bc7dbd.png) | ![Mobile - Sorting](https://user-images.githubusercontent.com/541093/216726074-5ff35361-c58f-4480-9342-72483a8ad2e3.png) |

**Comment by gibrown** [comment]
I'm not positive what the scope of the "refresh" is here, but figured I would throw in some thoughts.

I think we should be offering a lot more filtering options here. Ratings and filtering by ratings especially. All of the filtering should also include the count of the number of items (faceting). Pretty standard search design practice is to not have any dead ends which means we shouldn't be displaying filters if adding that filter will result in an empty results page.

The results also don't tell you much about the quality of the themes or how to pick them: ratings, number of installs, etc. It seems like we could display a lot more information.

There are a bunch of notes around filtering and sorting for plugins that seem applicable here: https://meta.trac.wordpress.org/ticket/2753

The "Features" list of filters feels like too much of a hodgepodge. Why not break them into more sections? I think using a sidebar would help here by grouping that list more.

The implementation of the filters entirely in a dropdown seems like a pretty bad search UX also. Why not a sidebar where users will actually be encouraged to engage with the results. Also why such a small search box at the top?

Overall feels like we should much more be thinking about this in terms of an e-commerce "purchase" search. e.g. Amazon etc. 

I also think we could/should be matching more than just what is in the content of the theme and also match against any reviews for the themes. This probably would require displaying highlighting of the results, but we could do that.
