### ISSUE TITLE
Layout: Commercial

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-theme-directory#18]
[Figma](https://www.figma.com/file/DQuNUBmyVbbtJNOqCSrAPH/Themes?node-id=2224%3A25776&t=I6uUwo2R6VQO0HX8-4)

![Commercial Themes](https://user-images.githubusercontent.com/7200686/215926893-c74bd1ab-79f7-4c7f-b325-8513c96c0493.png)

**Comment by ryelle** [comment]
@WordPress/meta-design For the grid of commercial themers, the box is meant to be the theme shop screenshot like on the current page, right? Is the haiku not shown on this new design?

I also see they've got the favorite & style variation icons, how did you see those working on this page?

**Comment by jasmussen** [comment]
For the prose, I'm not deep into the details here. I wonder if @thetinyl has any details? (Oh, and in case you'd like to be included in the meta-design ping, not sure if that's useful, let me know).

As far as favorite and style variation icons, we can omit those since [the list of commercial theme shops](https://wordpress.org/themes/commercial/) are external links.

**Comment by beafialho** [comment]
> For the grid of commercial themers, the box is meant to be the theme shop screenshot like on the current page, right?

That's right.

> Is the haiku not shown on this new design?

Which haiku are you referring to?

> I also see they've got the favorite & style variation icons, how did you see those working on this page?

My bad @ryelle, these should not be there. I'll remove them from the designs.

**Comment by ryelle** [comment]
When you hover over a theme shop's card, it shows the haiku - presumably the one the shop submitted when asking to be added to the page.

<img width="330" alt="Screenshot 2023-02-06 at 12 46 35 PM" src="https://user-images.githubusercontent.com/541093/217046313-314d8afa-e380-44c4-baa5-0a49ef20f243.png">

The hover action makes them pretty hidden, so it would be nice to use a different approach if they're still wanted on the page.

**Comment by thetinyl** [comment]
> For the prose, I'm not deep into the details here. I wonder if @thetinyl has any details?

@jasmussen Are you referring to the copy under the hero header? Trying to get my bearings to see if I can be of help. 

> (Oh, and in case you'd like to be included in the meta-design ping, not sure if that's useful, let me know).

If there's often copy/content questions that get lumped in to those pings, it could be useful. Thanks! 

For now, @ryelle I'm noticing a tiny typo in the 'Requirements' section at the bottom, in the second-to-last bullet "up-to-date" should not be hyphenated. (It'll end up matching the "up to date" in the bullet above.)

**Comment by jasmussen** [comment]
> Are you referring to the copy under the hero header? Trying to get my bearings to see if I can be of help.

Yes, just a sanity check, essentially. Thank you for looking 🙏

**Comment by beafialho** [comment]
> The hover action makes them pretty hidden, so it would be nice to use a different approach if they're still wanted on the page.

Ah, you're right. I missed that detail. I think that can work if we keep it in extra small to avoid adding too much empty space between items:
<img width="1315" alt="Captura de ecrã 2023-02-07, às 10 56 41" src="https://user-images.githubusercontent.com/65220155/217226421-8cc75b0a-adea-47ed-98f8-79a5d34a4d1f.png">
