### ISSUE TITLE
Layout: Author

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-theme-directory#19]
[Figma](https://www.figma.com/file/DQuNUBmyVbbtJNOqCSrAPH/Themes?node-id=2370%3A29452&t=I6uUwo2R6VQO0HX8-4)

_(removed wrong screenshot to prevent confusion)_

**Comment by beafialho** [comment]
Sorry, I must have left the wrong one in the Final page. Here's the correct mockup:

[Figma](https://www.figma.com/file/DQuNUBmyVbbtJNOqCSrAPH/Themes?node-id=2370%3A29452&t=H7EZ1UzuDa7EPmfj-4)

![Themes - Author](https://user-images.githubusercontent.com/65220155/216012712-f69a264d-58d5-40bc-b21d-544184b224c9.png)

![Mobile Themes - Author](https://user-images.githubusercontent.com/65220155/216012391-37e38bd0-7a7d-4e72-a5f7-395fbe0e5037.png)

**Comment by ryelle** [comment]
@WordPress/meta-design This page seems to be the only one with "by [author]" on the theme card, and since it's the Author's archive page it seems redundant. Should we add that to the main theme grid too? or should it be gone from everywhere?

**Comment by beafialho** [comment]
I imagined the author name should only show up below the theme name in this page @ryelle, similar to what the site does [now](https://wordpress.org/themes/author/wordpressdotorg/). However, removing it from everywhere also seems ok to me.

**Comment by ryelle** [comment]
huh. I wonder if that's because that page has no space for a "Themes by: AuthorName" header.

Since it would just link to the current page, let's leave it out. If we change our minds we can re-add it later.
