### ISSUE TITLE
Theme Directory should have a locale suggestion banner

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-theme-directory#27]
As requested in the original [Meta Trac ticket](https://meta.trac.wordpress.org/ticket/1864), the locale suggestion banner should appear on the theme directory page. Direction on where it should be located was [asked](https://www.figma.com/file/DQuNUBmyVbbtJNOqCSrAPH?node-id=2549:32274#372155019) in the Figma file and should ideally reuse the code to implement it on similar sites such as the [Documentation](https://wordpress.org/documentation) site.

**Comment by ryelle** [comment]
Done in https://github.com/WordPress/wporg-theme-directory/commit/a4dc92d1f4fa188b17265bf636121e4ebb256151
