### ISSUE TITLE
Theme Translations should be viewable directly

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-theme-directory#28]
Moving from meta trac: https://meta.trac.wordpress.org/ticket/5925

**Is your feature request related to a problem? Please describe.**
> When you look at an overview page of a plugin, you can quickly see at the right side in which languages it's translated.

> Yet, on theme pages, you only get a button that goes to translate.wordpress.org

**Describe the solution you'd like**
> Why the inconstancy? I think it could be helpful to see if a theme is translated or not like with the plugins.

**Comment by ryelle** [comment]
Duplicate of meta ticket https://meta.trac.wordpress.org/ticket/1383, we can use this issue to track.
