### ISSUE TITLE
New Theme: No screenshot in embed template

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-theme-directory#46]
The current theme has a custom embed template, which includes the theme screenshot.

| Current theme | Block theme |
|---|---|
| ![Screen Shot 2024-04-30 at 18 56 47-fullpage](https://github.com/WordPress/wporg-theme-directory/assets/541093/90667a65-7bf1-4344-9a48-bc93728cf82c) | ![Screen Shot 2024-04-30 at 18 56 41-fullpage](https://github.com/WordPress/wporg-theme-directory/assets/541093/2466e8f6-1f36-43f8-9763-18a258fa245d) |

**Comment by ryelle** [comment]
@dd32 Thanks for flagging! This makes sense to bring back to the block theme, do you think it needs more discussion?

**Comment by dd32** [comment]
I don't think this needs discussion; but personally I was wondering if it should be tweaked to match the new style slightly more.. mostly the large image is questionable I felt.

Only thing worth noting is that the image should either not be linked, or have it's alt tag set appropriately; ref: https://github.com/WordPress/wordpress.org/pull/136
