### ISSUE TITLE
Theme Directory Redesign: H1 size is very small

### ISSUE THREAD

**Issue by mathetos** [WordPress/wporg-theme-directory#49]
**Describe the bug**
The H1 for the new Theme Directory feels very small. 

The size is currently set at as `var(--wp--preset--font-size--heading-5)` which is the second smallest heading size in terms of the variables in the stylesheet
<img width="1213" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/930724/cd511a4f-7541-42cd-9aa8-2d157f53ddf4">

**Suggested Change**
It seems the H1 should be `var(--wp--preset--font-size--heading-1)`, but that feels a bit large. 

I'm suggesting to use `var(--wp--preset--font-size--heading-2)` instead of `var(--wp--preset--font-size--heading-5)`

Here's what that looks like:
<img width="1189" alt="image" src="https://github.com/WordPress/wporg-theme-directory/assets/930724/85988e25-511c-4b20-aa20-a00009ba4106">

**Additional context**
It kind of begs the question of why the variables for font-size are set the way they are if they aren't sufficient for the actual H1 on the screen.

**Comment by ryelle** [comment]
Hello, thanks for checking out the theme preview! This hasn't gone through any design review process yet, so these font sizes are pretty much placeholder at the moment. I've already heard from @WordPress/meta-design that they plan to do a typography review, so maybe we can use this issue to discuss the typography on the Theme Directory holistically.

>  It kind of begs the question of why the variables for font-size are set the way they are if they aren't sufficient for the actual H1 on the screen.

This type scale is used across the entire WordPress.org network, and in some cases we do want the fonts to be this big (the homepage, About subpages, etc), and they're used as-is there. In other areas of the site, that size is too large, so we just scale it down. I probably went too far with `heading-5` here, `heading-3` would match the current font-size of 36px.

**Comment by jasmussen** [comment]
Good issue, reasonable. The context for the current heading size is [this exploration](https://www.figma.com/file/DQuNUBmyVbbtJNOqCSrAPH/Themes?type=design&node-id=3260%3A7199&mode=design&t=h6i2YQxe4NImEJOg-1):

![Screenshot 2024-05-03 at 09 07 22](https://github.com/WordPress/wporg-theme-directory/assets/1204802/c571518d-f8af-4e16-aa15-70301c0a80fa)

36px feels like a good size for this heading. The thing to also be mindful of is to be responsible with the density and whitespace, so it doesn't push good content too far down. To that end, 36 is probably a good place to start, and then we can go from there.
