### ISSUE TITLE
Theme Directory Redesign: Make the translation link more visible

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-theme-directory#51]
**Is your feature request related to a problem? Please describe.**

As [noted](https://wordpress.slack.com/archives/C04U953K77A/p1714723000516829) in slack's `#website-redesign` channel, the link to translate a theme is too subtle compared to Support and Report sections.

<img src="https://github.com/WordPress/wporg-theme-directory/assets/895819/77f64f99-fc84-4044-9119-79c56486eeca" alt="Screenshot of sidebar in theme details page" width=200>

**Describe the solution you'd like**

Change the link to be a button, just like Support and Report are.

**Comment by StevenDufresne** [comment]
Noting that in the plugin directory, we've decide to remove the buttons in favour of links.

https://github.com/WordPress/wordpress.org/issues/263

**Comment by ryelle** [comment]
The other items have been converted to links (see #62, https://github.com/WordPress/wporg-theme-directory/commit/9421808cddec17c073df71823fc2b6733bfd48f9). Also see #28 for improving this section in general.
