### ISSUE TITLE
Unify secondary navigation items across themes, patterns, plugins

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#55]
Across themes, patterns, plugin directories there are secondary navigation items we can improve the consistency of. Themes:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/fc196ecc-63aa-4ab5-bc46-6b564fb88bfc)

Plugins:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/2e2ce46c-4c22-4725-a185-a09c31ccc808)

Patterns:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/4b03819a-dbfd-44dd-b276-006cb1fa210a)

Using either title case or sentence case (with a small preference for leaning towards sentence case across) has been noted for some of the other directories. But at least it should be consistent. Across:

* Use "My favorites" or "My Favorites", not just "Favorites"
* Use the same case across.

**Comment by ryelle** [comment]
I think we've standardized on sentence case everywhere, so we should stick with "My favorites" — right @thetinyl?

**Comment by thetinyl** [comment]
@ryelle Confirming sentence case!

**Comment by ryelle** [comment]
Cool, then this can be closed for the theme directory, and individual issues should be opened in the Pattern directory and Plugins repos for updating those instances.
