### ISSUE TITLE
Improve preview

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#64]
![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/97363516-d6a8-42d0-8e4a-49b817ae195f)

Overall looks good. The sidebar has been made useful with patterns and style variations. A few notes:

* Should we move the Wide, Medium, and Narrow buttons to the top, to match their placement for pattern resizing?
* Perhaps we should make the Download button slightly smaller ([50px big button](https://href.li/?https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=152%3A395&mode=design&t=d6WQT7gcL6lwOyaE-1)).
* Style variations and Patterns should both have the same heading style.
* Either we show the count for both variations and patterns, or neither. Either seems fine.

Finally, the download button is sticky at the bottom so it’s easy to see, that’s good. But it’s a long way to tab if you’re just using the keyboard, having to go through style variations and patterns first. Maybe we can move it to the top, right after the description? A bit like [this sketch](https://href.li/?https://www.figma.com/file/DQuNUBmyVbbtJNOqCSrAPH/Themes?type=design&node-id=3260%3A7199&mode=design&t=jQWFGeS5iaOhRZtr-1):

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/5c19c3e7-45e4-42d9-bcf5-d7ad48f12734)

**Comment by ryelle** [comment]
Just FYI, I've moved this back to pending discussion & added the Needs Design Feedback label since there are still unanswered design questions here.

> Should we move the Wide, Medium, and Narrow buttons to the top, to match their placement for pattern resizing?

We don't have the same resizing issue that we initially had with the toggles on Patterns, and this UI is very different from that one IMO. Plus, this selector is at the bottom of the sidebar on the old theme, so I would lean to leaving it at the bottom. 

> Style variations and Patterns should both have the same heading style.

Which one?

> Perhaps we should make the Download button slightly smaller

Does the "small" variation work?

<img width="333" alt="Screenshot 2024-05-13 at 11 15 13 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/326d7054-5784-4f4a-9b48-46a2ad7b1e70">

> Maybe we can move it to the top, right after the description?

Sure, and styles/patterns would appear after that? Should there be any separator or extra space under the zip name?

**Comment by jasmussen** [comment]
> We don't have the same resizing issue that we initially had with the toggles on Patterns, and this UI is very different from that one IMO. Plus, this selector is at the bottom of the sidebar on the old theme, so I would lean to leaving it at the bottom.

We can go with that, sure, can always revisit.

> > Style variations and Patterns should both have the same heading style.
> 
> Which one?

I opened a lot of issues yesterday, and thanks for diving in, I should've been more clear.

This EB Garamond heading style works well:
![Screenshot 2024-05-14 at 09 12 56](https://github.com/WordPress/wporg-theme-directory/assets/1204802/bad39b33-fcd6-4e60-99bf-4d689d4296d7)

Works better than the paragraph style here:

![Screenshot 2024-05-14 at 09 13 00](https://github.com/WordPress/wporg-theme-directory/assets/1204802/ce16c6f6-be0b-4c53-a613-29780e7d4806)

So if it could be just a heading for style variations in similar style to Patterns, that would work well.

> Does the "small" variation work?

Yes.

> Sure, and styles/patterns would appear after that? Should there be any separator or extra space under the zip name?

Most likely. Here's a quick inspector sketch of how it could look, all of it coming together:
![Screenshot 2024-05-14 at 09 18 43](https://github.com/WordPress/wporg-theme-directory/assets/1204802/b6a3a872-aa71-45ff-a0cc-955956f3d75c)

Note here the font size of the Style variations and Patterns headings is the H5 font size of 26px. Let me know if that works for you.
