### ISSUE TITLE
Consider the theme count

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#68]
The old site shows what looks like a precise theme count:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/d271698a-2ba8-499f-a78c-ea9293a24930)

The new one shows instead “Over 10,000 free themes to customize your WordPress site”, which reads a little better. At the same time, we do show what appears to be a precise count on the plugins page:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/dfb3010f-bcef-4277-b61b-3fdafe74744e)

Perhaps we should show precise counts in both places? Or fuzzy counts in both places?

Related to both, we now have this search box plus filtered count:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/07fc7506-5117-4a5a-bbe5-9b15201a917f)

There’s a bit of confusion with this count, since it’s less than 10000. This is further made confusing because if I press “Next” in the pagination, it shows a new count:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/fa2a2e66-6f9e-43c1-9ba7-ce77d608ea03)

Adjacent to all of this, there was feedback on the plugin directory that search, especially on the landing page, was not quite prominent enough. Similar feedback might apply here. Should we/can we apply the same solution here?

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/a17d55c4-1df7-402e-8d0f-693aa5a32432)

The main challenge there is the lack of filters. All is to say, the filter-bar/search componentry keeps coming up, and it may be worth taking a look soon. A very quick test:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/1cb11da5-a4f5-45f3-9078-79c25aa5a1d6)

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/336179c6-846a-435e-b023-3e9ea1f3d6c8)

**Comment by ryelle** [comment]
Okay, I've had time to read through this a bit more thoroughly and I think there are a few things happening here.

1- Header string: Old theme uses exact number “Add style to your WordPress site! Browse 12,252 free themes.”, new theme uses rounded number “Over 10,000 free themes to customize your WordPress site”.

Personally I like the rounded number better, but we use an exact number on plugins so we should probably match that. Any thoughts @thetinyl?

2- Query total block is showing different counts on paged queries

~I'm not sure why, this is definitely a bug.~ Figured this one out, the /page/X requests were not using the popular browse query, so /browse/new/page/2/ and /page/2/ were functionally the same. Fix in progress.

3- Query total is less than 10,000

The homepage query is "by popularity", so it only shows themes that have popularity meta values. It also only shows themes that have been updated within 2 years to 2 weeks ago. So this cuts out a good portion of older themes that make up the 12,000+ published themes. The "Latest" tab should show all themes ever.

We had a similar issue on showcase— we can override the query total on Popular to say the total amount of themes, but Themes has pagination and that won’t match up (ex, it will say 545 pages of 12, which is only 6000).

Or we could use a different approach, and update the label to say "6,460 popular themes"? Needs work 😅 

> The main challenge there is the lack of filters. All is to say, the filter-bar/search componentry keeps coming up, and it may be worth taking a look soon.

Let's keep this discussion in https://github.com/WordPress/wporg-mu-plugins/discussions/603 so we can keep consistent with all the sites.

**Comment by ryelle** [comment]
> 2- Query total block is showing different counts on paged queries

Deployed this fix https://meta.trac.wordpress.org/changeset/13703

**Comment by jasmussen** [comment]
> Or we could use a different approach, and update the label to say "6,460 popular themes"? Needs work 😅

I wonder if we could just not show the count next to search on the landing page, in this particular case?

**Comment by ryelle** [comment]
Is the count OK on this page? https://wordpress.org/themes/page/2/ — in other words, is the issue just when the "Over 10,000 free themes to customize your WordPress site" header is visible?

**Comment by jasmussen** [comment]
I see this number:

![Screenshot 2024-05-15 at 16 55 39](https://github.com/WordPress/wporg-theme-directory/assets/1204802/1691fbb8-c1a1-4721-8874-c826e5ab14ed)

Mainly it's the confusion about what the number is about. I see 10000 mentioned on the homepage, 6463 here. I can do the math and figure out, oh it's probably just in the "popular" category. But I wonder if in this particular case it wouldn't be better to omit the number? I realize that's another edgecase.

**Comment by ryelle** [comment]
Yes, that number. I was asking if it should only be removed from the homepage itself (literally just `/`) or also the next pages of the same query (`/page/2/`, etc). Is the issue only when "Over 10,000 free themes to customize your WordPress site" is on screen?

**Comment by jasmussen** [comment]
I'm happy to try keeping that number there. Especially if it's simpler. But it may also help to denote, `6,463 popular themes`.

**Comment by thetinyl** [comment]
To quickly backtrack to the round number vs. explicit theme count... I think it boils down to what we're trying to communicate here. 

A specific number shows an upward count, indicating that the Directory is alive—that more themes are being added regularly. However, I don't know if that's something that most visitors (particularly new visitors) are going to keep track of.

On the other hand, the number of options available—whether it's 10k or 12,367—is vast no matter how you look at it. It's a lot of choice. (Sometimes, having that much choice can even seem overwhelming.)

If we had a small number of themes, I can see how showcasing the exact count would be a benefit. In this case, I don't see the benefit of being specific when the fuzzy number works just as well. I'd say the same for the Plugin Directory—that it, too, could accomplish what it needs to with a rounded number. And, like you both mentioned, the rounded number looks/reads better, too. 

> Is the issue only when "Over 10,000 free themes to customize your WordPress site" is on screen?

I think this is the main issue. We're setting up the context here that this is the homepage for the Directory, and these are all the themes. I don't think it's clear enough that the themes are pre-categorized to "Popular", so the second theme count would need that context if it stays.

**Comment by ryelle** [comment]
For the theme query total number— I'm not being clear about what I'm asking, so I've just gone ahead and removed the number from the homepage, but left it on the subsequent pages. If that was wrong, I can also hide here. You can try it out on w.org/themes now.

Here's a screen recording to be clear— the first screen is the homepage, with not count. Then I go to page 2 of the home query, which is still "popular". The count is seen here (this was the question). Then I go to Block Themes, where the count appears (as it should be, no change here).

https://github.com/WordPress/wporg-theme-directory/assets/541093/57cfee2a-a0c4-4be5-b5eb-9350b2f978d8

> If we had a small number of themes, I can see how showcasing the exact count would be a benefit. In this case, I don't see the benefit of being specific when the fuzzy number works just as well. I'd say the same for the Plugin Directory—that it, too, could accomplish what it needs to with a rounded number. And, like you both mentioned, the rounded number looks/reads better, too.

Okay great, sounds like we can stick with a rounded count. What do you think about using a thousands-rounded version of the real count? ex, "Over 12,000 free themes to customize your WordPress site." and "Extend your WordPress experience! Browse 59,000 free plugins."?

**Comment by thetinyl** [comment]
> the first screen is the homepage, with not count. Then I go to page 2 of the home query, which is still "popular". The count is seen here (this was the question).

I think for now this is fine. Thanks for the video reference! I still wonder if it's clear enough that it's the "Popular" category, especially since—even on page 2—that category is auto-selected for the visitor (unless they're selecting back to it while browsing). Without the "Over 12k themes..." hanging around though, it's likely less confusing/inconsistent seeming. 

> What do you think about using a thousands-rounded version of the real count? ex, "Over 12,000 free themes to customize your WordPress site." and "Extend your WordPress experience! Browse 59,000 free plugins."?

I think that works! Good thought. 

It'd be even better if we were at over 60,000 plugins (it's a nicer looking number than 59,000, I think), but... ah well. It'll happen soon enough. 

I'm guessing we'll need to be mindful of these counts as more theme/plugin submissions are reviewed and added. There's no way to make the round number dynamic by the thousand, is there?

**Comment by ryelle** [comment]
>  I still wonder if it's clear enough that it's the "Popular" category, especially since—even on page 2—that category is auto-selected for the visitor (unless they're selecting back to it while browsing). 

Yeah, I think that ties into the issue on https://github.com/WordPress/wporg-mu-plugins/discussions/603.

> I'm guessing we'll need to be mindful of these counts as more theme/plugin submissions are reviewed and added. There's no way to make the round number dynamic by the thousand, is there?

That's what I meant 🙂  We can round the real number to the thousands for display. Well, round-down, so we're not saying there are more than there are. Once we hit 60,000+, it would update dynamically.

**Comment by thetinyl** [comment]
> That's what I meant 🙂 We can round the real number to the thousands for display. Well, round-down, so we're not saying there are more than there are. Once we hit 60,000+, it would update dynamically.

Huzzah! One less thing to keep track of. Thanks for the clarification. 👍

**Comment by fcoveram** [comment]
I like @ryelle's idea of hiding the count in homepage and show it back in the results pages, it address the confusion of having multiple numbers on the screen.

I agree with @thetinyl that "Popular" category is not clearly conveyed, but we can revisit this page and land on a solution similar Showcase where homepage works like a curated page once the style refresh stage is done.

**Comment by ryelle** [comment]
I think all the feedback has been addressed here. If anything else needs to be updated, let's do that in new issues.
