### ISSUE TITLE
Consider open-sourcing the wporg-ratings plugin

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-theme-directory#7]
If the wporg-ratings plugin was in a public repo, we could install it in this environment and test against it properly instead of using a mock (#1).

Before that could happen, someone needs to do a quick review and see if there are any glaring security or quality issues preventing the code from being made public.

If it's an unacceptable risk then I guess we can just expand the mock class a little as needed for testing.

If there are no blockers, the easiest place to put it for now is probably within this repo. We could move it elsewhere later when the site is launched.

**Comment by tellyworth** [comment]
After chatting with @dd32, let's go ahead and open-source the plugin. Necessary steps that I can think of off the top of my head:

- [ ] Review the old plugin for security.
- [ ] Fix/rewrite any insecure code, while maintaining back compat with the existing storage method.
- [ ] Remove any old cruft.
- [ ] Add the improved version to this repo, in source/wp-content/plugins.
- [ ] Create a script in env that will import some sample data or generate random data for local testing.

Anything else needed there? @pkevan why don't you take a shot at that.

**Comment by pkevan** [comment]
👀 taking a look

**Comment by pkevan** [comment]
probably going to need commit access to the repo to add the plugin (not needed immediately)

**Comment by pkevan** [comment]
i've tested out removing the include in https://dotorg.trac.wordpress.org/changeset/19921/ and all seems good so far.
