### ISSUE TITLE
Hitting return after search updates URL with `?`

### ISSUE THREAD

**Issue by pkevan** [WordPress/wporg-theme-directory#73]
**Describe the bug**
I realise this isn't the functionality of the search, but came across this whilst looking at another bug (which seemed to go away!)

When you hit the return key (keyboard), you it adds an additional `?` into the URL, so a search for `test` followed by the return key results in the URL being updated with `/themes/search/test/?`.

If you edit the search, the URL corrects itself (removes the `?`).

This is only present in the current theme (not the new one), so unsure how relevant it is, but noting for completeness.

**Comment by ryelle** [comment]
We've just enabled the new theme, so I'm going to close this issue 🙂
