### ISSUE TITLE
Theme Homepage should include external arrow if link is external.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-theme-directory#76]
In the theme's meta section we link the theme's homepage. If it's an external site, we should add the external link indicator.

You can test it on this page:
https://wordpress.org/themes/neve/

## ScreenShot
<img width="388" alt="Screenshot 2024-05-23 at 7 41 42 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/761d916f-cd54-403c-92ac-c1632ae73977">

**Like this**
<img width="137" alt="Screenshot 2024-05-23 at 7 43 13 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/5b726ce1-9af8-4eb8-ada2-5de8f0d6793e">

**Comment by ryelle** [comment]
Technically that link should always be external, it's only the core Twenty* themes that link back to wporg (as part of the required theme guidelines) — so I think we could just add the `external-link` style always.
