### ISSUE TITLE
Improve grid layout when viewport is `600px - 750px`

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-theme-directory#77]
**Describe the bug**
When the viewport width is between 600-700px the image grid feels a bit crowded and long theme titles start to break to new lines.

**Expected behavior**
Can we break to 2x2 at 700px?

**Screenshots**
| Current @ `750px` | After @ `750px` |
|--------|--------|
| <img width="705" alt="Screenshot 2024-05-23 at 7 44 18 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/c183aff6-b120-4a23-9225-4e3c0754c40a"> | <img width="748" alt="Screenshot 2024-05-23 at 9 05 55 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/98bfd1dd-582d-4be4-ba92-d4a67aca6d90"> | 

**Steps to Reproduce**
1. Visit https://wordpress.org/themes/?new-theme=1.
2. Adjusts browser window width.

**Comment by ryelle** [comment]
I wonder if something changed, I thought I did have a 2-column breakpoint… in any case, yes let's do that.
