### ISSUE TITLE
Author archive page should have visible heading

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-theme-directory#78]
**Is your feature request related to a problem? Please describe.**
Theme creators' page looks very similar to the search results one and it's not very clear that is listing themes from a creator.

![Screenshot of theme creator's index page](https://github.com/WordPress/wporg-theme-directory/assets/895819/daa5c569-85e8-401f-a8b9-6c6478678eca)

**Describe the solution you'd like**
Add a text saying "by [creator-name]" next to the results label on the right side of the search input. For instance, in [this case](https://wordpress.org/themes/author/cretathemes/) it would say "27 themes by Creta Themes".

If this solution is too subtle, we could consider adding a heading like the `h1` of theme details page saying "[creator-name]'s themes" or something similar

**Comment by ryelle** [comment]
The page already has a hidden heading for accessibility (I mentioned in [this plugns thread](https://github.com/WordPress/wordpress.org/issues/308#issuecomment-2101323846) how that's kind of strange, that only the screen-reader users get that benefit); I could make that visible? Here's an attempt with some style:

<img width="1264" alt="Screenshot 2024-05-23 at 12 48 23 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/f68376b2-f52b-498c-9ce8-9059cece2f4e">


That could be just on authors, or I could make that visible everywhere:

<img width="1233" alt="Screenshot 2024-05-23 at 12 48 36 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/ee1928f6-402f-4c27-9904-d69c341b3f52">

Or we could bring in breadcrumbs like patterns:

<img width="1307" alt="Screenshot 2024-05-23 at 12 48 58 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/7b10716b-4fe5-4fb0-9387-cf471044a13d">

Finally, just noting that this _is_ visible on scroll:

<img width="1362" alt="Screenshot 2024-05-23 at 12 49 28 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/565de6ed-595c-4df9-b529-b0130aa84e42">


What do you think?

**Comment by fcoveram** [comment]
Making the heading visible on Authors is enough. I didn't notice the label in local nav when scrolling down, so showing the heading in both local nav and below search and filter bar looks good.
