### ISSUE TITLE
Add a label in fav action

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-theme-directory#79]
**Is your feature request related to a problem? Please describe.**
The heart icon for adding a theme to my favorites looks floating in space without other visual traits that attach it to the page.

![Screenshot of header of theme details page. Arrow pointing out the heart icon](https://github.com/WordPress/wporg-theme-directory/assets/895819/8844aafc-3ece-4ade-8871-4638e5139ac1)

**Describe the solution you'd like**
Add a label to the button's left side:
* For the not added state: "Add to favorites"
* For the added state: "Added". in this case, the label could disappear after 2 secs.

**Describe alternatives you've considered**
If this solution takes big effort, we could just added a label for the first state; before clicking on the heart.

**Comment by ryelle** [comment]
Should the text just be floating next to it, or do you want an outline button like on patterns?

<img width="1229" alt="Screenshot 2024-05-23 at 10 08 23 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/541093/889198ef-47d2-4239-842d-0a791746c13d">

**Comment by fcoveram** [comment]
The outline version like in Patterns looks good 👍
