### ISSUE TITLE
Align button to the left in Submit a theme page

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-theme-directory#82]
**Is your feature request related to a problem? Please describe.**
The "Upload your theme" button looks strange in the middle of the page.

<img src="https://github.com/WordPress/wporg-theme-directory/assets/895819/28569c6c-8f46-411b-b70d-aa9a98605ed7" src="Screenshot of Submit a theme page" width=550>

**Describe the solution you'd like**
Align the button to the left.

**Comment by ryelle** [comment]
I fixed this yesterday (@jasmussen reported it in #57). Are you still seeing the centered button?

**Comment by fcoveram** [comment]
I see it good now ✅ Thanks
