### ISSUE TITLE
Inconsistent padding when viewing a "community" theme.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-theme-directory#86]
**Describe the bug**
The padding between the commercial/community paragraph that is added when the them has a category is not consistent there appears to be an extra 10px under the buttons.

**Screenshots**
<img width="392" alt="Screenshot 2024-05-24 at 9 20 05 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/10229856-dfce-47dd-843c-be6ce9a77eca">

Example theme with link:
https://wordpress.org/themes/twentytwentyfour/

Example theme without link:
https://wordpress.org/themes/oceanwp/

**Comment by ryelle** [comment]
You're right, the meta block has a `spacing--30` top margin, it should be 20 to be consistent.
