### ISSUE TITLE
The "Popular" category has 542 pages of themes.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-theme-directory#89]
**Describe the bug**
When I load the page, the default category is "Popular". When I scroll down to see the pagination, it says there are 542 pages of "Popular" themes which is roughly half the directory. 

I suspect this is a legacy from the existing one where it was an infinite list and therefore there was no paging, but it's a bit weird now that we show pagination. 

Should we add a proper limit to "Popular"?

**To Reproduce**
1. Go to wp.org/themes
2. Notice the Popular section is selected
3. Notice the 542 pages of theme.

**Expected behavior**
I would expect there to only be a handful pages of popular themes.

**Screenshots**

<img width="1428" alt="Screenshot 2024-05-24 at 9 42 56 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/1a537b03-1c8b-4f5e-948c-52bbeee126e4">

**Comment by ryelle** [comment]
Despite the UI, this isn't a category of "Popular", it's all themes ordered by popularity — though it is limited by themes updated in the last two years, older than two weeks.

I don't think we should be changing how this query works, that seems like a larger-than-refresh issue.

**Comment by ryelle** [comment]
I've moved this & some other comments over to a new discussion: https://github.com/WordPress/wporg-theme-directory/discussions/124
