### ISSUE TITLE
Increase darkness of `.wp-block-wporg-screenshot-preview` border.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-theme-directory#92]
**Describe the bug**
The border on `.wp-block-wporg-screenshot-preview` is `light-grey-2` which doesn't match the screenshot border and is too light, especially when the pattern or style variations have a white background.

| Before | After |
|--------|--------|
| <img width="722" alt="Screenshot 2024-05-24 at 10 00 50 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/80bf446a-7436-439e-a45a-99f0e8a60b9e"> | <img width="702" alt="Screenshot 2024-05-24 at 10 00 42 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/07fe859d-ef35-4b17-b530-35f10f76290b"> |
| <img width="709" alt="Screenshot 2024-05-24 at 10 00 11 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/4f5979da-3bc2-48e0-b0eb-b3b6bde4f459"> |  <img width="715" alt="Screenshot 2024-05-24 at 10 00 28 AM" src="https://github.com/WordPress/wporg-theme-directory/assets/1657336/9d5ded13-8169-4b27-8440-3dae18cc1743"> | 

Theme Link: 
https://wordpress.org/themes/twentytwentyfour/

**Comment by ryelle** [comment]
@WordPress/meta-design What do you think? It looks like we have a few different borders going on on this page. The main screenshot uses black at 15% opacity, currently the style variations and patterns use light-grey-2 (which matches the grey background on patterns now (not on the preview yet)), and light-grey-1 is used on the meta & variation nav arrows.

![Screen Shot 2024-05-31 at 17 21 02](https://github.com/WordPress/wporg-theme-directory/assets/541093/4c45a084-b700-4a60-80da-41917908d0e9)

If we switch style variations and patterns to light-grey-1, they'll be more consistent at least.

![Screen Shot 2024-05-31 at 17 32 53](https://github.com/WordPress/wporg-theme-directory/assets/541093/9d8eed38-ac4d-40d8-b4f8-dd346ffc8802)

**Comment by jasmussen** [comment]
Light gray 1 works, good to unify this, good issue.

**Comment by fcoveram** [comment]
Agree with @jasmussen, it looks good
