### ISSUE TITLE
Theme hover style: Unify with Plugin directory

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-theme-directory#96]
The hover style in the theme directory is a black border:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/255daa3d-f53a-456d-813c-68248b2b797a)

In the plugin directory, it's a gray background:

![Image](https://github.com/WordPress/wporg-theme-directory/assets/1204802/75837345-700f-4ab1-ac99-d4f26d6124b4)

We should update so these are the same. I'd recommend trying to absorb the plugin directory style in the theme directory. It's mostly decorative, after all, and it might be less confusing as far as focus styles.

**Comment by ryelle** [comment]
Should I also revert the charcoal border suggested here https://github.com/WordPress/wporg-theme-directory/issues/83? Does this impact the hover state of the pattern and style cards?

**Comment by jasmussen** [comment]
I hadn't seen that, thanks for bringing it up. I wouldn't want to undo @fcoveram's suggestion, so we can go the other direction too, update the plugin directory hover style to be similar to this.

**Comment by fcoveram** [comment]
Sorry for the lack of coordination. I agree with updating the plugin directory to inherit the border behavior.

**Comment by ryelle** [comment]
Works for me 😄  I'll close this and you can open an issue in https://github.com/WordPress/wordpress.org for updating the plugin directory. Should the Pattern Directoy also be updated? (would be another issue in https://github.com/WordPress/pattern-directory/)

**Comment by jasmussen** [comment]
Moved to https://github.com/WordPress/wordpress.org/issues/324. Pattern directory let's leave as is for now, it's a slightly more unique case, the gray background works well there, but that wouldn't work for themes and plugins.
