### ISSUE TITLE
Downloads Per Day Graph

### ISSUE THREAD

**Issue by nickhamze** [WordPress/wporg-theme-directory#99]
This graph is a limited usefulness to the average user. I think the most important signal is the number of active users and that is available up at the top anyway. 

<img width="809" alt="Screenshot 2024-05-30 at 5 43 04 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/158918/fb9535c8-cbba-4d22-8934-5d0d1cb73a89">

**Comment by ryelle** [comment]
I think we can improve what/how we show this data, but that's not part of the current project. Can you [create a discussion](https://github.com/WordPress/wporg-theme-directory/discussions) to brainstorm some ideas for the next redesign?
